In [23]:
import pandas as pd

In [26]:
df = pd.read_csv('df_espumosos_ok2.csv')

In [27]:
df.head

<bound method NDFrame.head of                                                     Url        ID  \
0     https://www.vivino.com/ES/es/vinos-sanz-fri-sa...   4559173
1     https://www.vivino.com/ES/es/castellblanc-cast...   2453836
2     https://www.vivino.com/ES/es/palacio-de-bornos...   2329608
3     https://www.vivino.com/ES/es/palacio-de-bornos...   4243274
4     https://www.vivino.com/ES/es/xenius-cava-semi-...   2125572
...                                                 ...       ...
1912  https://www.vivino.com/ES/es/agrapart-fils-exp...   1455336
1913  https://www.vivino.com/ES/es/francis-orban-cha...   3979388
1914  https://www.vivino.com/ES/es/r-lenoble-gentilh...   2304743
1915  https://www.vivino.com/ES/es/duval-leroy-femme...  11003457
1916  https://www.vivino.com/ES/es/charles-heidsieck...   1316061

                                                 Nombre            Año  \
0                                Fri Sanz Te Semi Dulce           2013
1                                         Cava BrutN.V.  No disponible
2                            Verdejo 5,5° FrizzanteN.V.  No disponible
3                             Rosado 5,5° FrizzanteN.V.  No disponible
4                                    Cava Semi-SecoN.V.  No disponible
...                                                 ...            ...
1912                         EXP. Brut Nature Champagne           2019
1913                                Millésimé Champagne           2016
1914  Gentilhomme Blanc de Blancs Brut Champagne Gra...  No disponible
1915                     Femme de Champagne Brut Nature           2002
1916                                  Champagne Charlie           2017

         País               Región                        Bodega  \
0      España                Rueda                    Vinos Sanz
1      España                 Cava  Castellblanc (Castellblanch)
2      España      Castilla y León             Palacio de Bornos
3      España      Castilla y León             Palacio de Bornos
4      España                 Cava                        Xènius
...       ...                  ...                           ...
1912  Francia              Champán               Agrapart & Fils
1913  Francia              Champán                 Francis Orban
1914  Francia  Champagne Grand Cru                       Lenoble
1915  Francia  Champagne Grand Cru                   Duval-Leroy
1916  Francia              Champán             Charles Heidsieck

       Tipo de vino                                    Uva  Precio Valoración  \
0     Vino espumoso                                Verdejo    5.97        3.8
1     Vino espumoso           Macabeo, Xarel-lo, Parellada    6.10        3.5
2     Vino espumoso                          No disponible    5.80        3.8
3     Vino espumoso                          No disponible    5.80        3.9
4     Vino espumoso           Macabeo, Xarel-lo, Parellada    5.80        3.6
...             ...                                    ...     ...        ...
1912  Vino espumoso                             Chardonnay  342.91        4.3
1913  Vino espumoso              Chardonnay, Pinot Meunier  101.18        4.0
1914  Vino espumoso                             Chardonnay      92        4.3
1915  Vino espumoso                 Chardonnay, Pinot Noir  279.99        4.4
1916  Vino espumoso  Chardonnay, Pinot Noir, Pinot Meunier     885        4.5

     Contenido de alcohol                                          Maridajes
0                      11  Marisco, Aperitivos y tentempiés, Pescado blan...
1                       5  Marisco, Aperitivos y tentempiés, Pescado blan...
2                       5  Marisco, Aperitivos y tentempiés, Pescado blan...
3                       5  Marisco, Aperitivos y tentempiés, Pescado blan...
4           No disponible  Marisco, Aperitivos y tentempiés, Pescado blan...
...                   ...                                                ...
1912                   13  Cerdo, Marisco, Pescado azul (salmón, atún, et...
1913                   12  Cerdo, Marisco, Pescado azul (salmón, atún, et...
1914                   12  Cerdo, Marisco, Pescado azul (salmón, atún, et...
1915                   12  Cerdo, Marisco, Pescado azul (salmón, atún, et...
1916                   12  Cerdo, Marisco, Pescado azul (salmón, atún, et...

[1917 rows x 13 columns]>

In [28]:
#Lista de columnas a verificar (excluyendo 'url' e 'ID')
columns_to_check = [ 'Año', 'País', 'Región', 'Bodega', 'Tipo de vino']

# Filtrar filas donde todas las columnas tienen "No disponible"
df_missing = df[df[columns_to_check].eq('No disponible').all(axis=1)]

# Mostrar el DataFrame con las filas que tienen "No disponible" en todas las columnas
print("\nFilas con 'No disponible' en todas las columnas:")
print(df_missing)

# Eliminar esas filas del DataFrame original
df = df[~df.index.isin(df_missing.index)]

# Mostrar el DataFrame original después de eliminar las filas
print("\nDataFrame Original después de eliminar las filas con 'No disponible':")
print(df)

Filas con 'No disponible' en todas las columnas:
Empty DataFrame
Columns: [Url, ID, Nombre, Año, País, Región, Bodega, Tipo de vino, Uva, Precio, Valoración, Contenido de alcohol, Maridajes]
Index: []

DataFrame Original después de eliminar las filas con 'No disponible':
                                                    Url        ID  \
0     https://www.vivino.com/ES/es/vinos-sanz-fri-sa...   4559173
1     https://www.vivino.com/ES/es/castellblanc-cast...   2453836
2     https://www.vivino.com/ES/es/palacio-de-bornos...   2329608
3     https://www.vivino.com/ES/es/palacio-de-bornos...   4243274
4     https://www.vivino.com/ES/es/xenius-cava-semi-...   2125572
...                                                 ...       ...
1912  https://www.vivino.com/ES/es/agrapart-fils-exp...   1455336
1913  https://www.vivino.com/ES/es/francis-orban-cha...   3979388
1914  https://www.vivino.com/ES/es/r-lenoble-gentilh...   2304743
1915  https://www.vivino.com/ES/es/duval-leroy-femme...  11003457
1916  https://www.vivino.com/ES/es/charles-heidsieck...   1316061

                                                 Nombre            Año  \
0                                Fri Sanz Te Semi Dulce           2013
1                                         Cava BrutN.V.  No disponible
2                            Verdejo 5,5° FrizzanteN.V.  No disponible
3                             Rosado 5,5° FrizzanteN.V.  No disponible
4                                    Cava Semi-SecoN.V.  No disponible
...                                                 ...            ...
1912                         EXP. Brut Nature Champagne           2019
1913                                Millésimé Champagne           2016
1914  Gentilhomme Blanc de Blancs Brut Champagne Gra...  No disponible
1915                     Femme de Champagne Brut Nature           2002
1916                                  Champagne Charlie           2017

         País               Región                        Bodega  \
0      España                Rueda                    Vinos Sanz
1      España                 Cava  Castellblanc (Castellblanch)
2      España      Castilla y León             Palacio de Bornos
3      España      Castilla y León             Palacio de Bornos
4      España                 Cava                        Xènius
...       ...                  ...                           ...
1912  Francia              Champán               Agrapart & Fils
1913  Francia              Champán                 Francis Orban
1914  Francia  Champagne Grand Cru                       Lenoble
1915  Francia  Champagne Grand Cru                   Duval-Leroy
1916  Francia              Champán             Charles Heidsieck

       Tipo de vino                                    Uva  Precio Valoración  \
0     Vino espumoso                                Verdejo    5.97        3.8
1     Vino espumoso           Macabeo, Xarel-lo, Parellada    6.10        3.5
2     Vino espumoso                          No disponible    5.80        3.8
3     Vino espumoso                          No disponible    5.80        3.9
4     Vino espumoso           Macabeo, Xarel-lo, Parellada    5.80        3.6
...             ...                                    ...     ...        ...
1912  Vino espumoso                             Chardonnay  342.91        4.3
1913  Vino espumoso              Chardonnay, Pinot Meunier  101.18        4.0
1914  Vino espumoso                             Chardonnay      92        4.3
1915  Vino espumoso                 Chardonnay, Pinot Noir  279.99        4.4
1916  Vino espumoso  Chardonnay, Pinot Noir, Pinot Meunier     885        4.5

     Contenido de alcohol                                          Maridajes
0                      11  Marisco, Aperitivos y tentempiés, Pescado blan...
1                       5  Marisco, Aperitivos y tentempiés, Pescado blan...
2                       5  Marisco, Aperitivos y tentempiés, Pescado blan...
3                       5  Marisco, Aperitivos y tentempiés, Pescado blan...
4           No disponible  Marisco, Aperitivos y tentempiés, Pescado blan...
...                   ...                                                ...
1912                   13  Cerdo, Marisco, Pescado azul (salmón, atún, et...
1913                   12  Cerdo, Marisco, Pescado azul (salmón, atún, et...
1914                   12  Cerdo, Marisco, Pescado azul (salmón, atún, et...
1915                   12  Cerdo, Marisco, Pescado azul (salmón, atún, et...
1916                   12  Cerdo, Marisco, Pescado azul (salmón, atún, et...

[1917 rows x 13 columns]

In [29]:
df_missing.shape

(0, 13)

In [30]:
df.shape

(1917, 13)

In [25]:
# Guardar df en un archivo CSV
df.to_csv('df_espumosos_ok.csv', index=False)

# Guardar df_missing en un archivo de texto
df_missing['Url'].to_csv('df_missing.txt', index=False, header=True, sep='\t')

In [31]:
# Cargar ambos archivos CSV en DataFrames
df1 = pd.read_csv('df_espumosos_ok.csv')  # Cambia por la ruta de tu primer archivo
df2 = pd.read_csv('df_espumosos_ok2.csv')  # Cambia por la ruta de tu segundo archivo

# Concatenar los DataFrames
df_combined = pd.concat([df1, df2], ignore_index=True)

# Guardar el DataFrame combinado en un nuevo archivo CSV
df_combined.to_csv('all_espumosos_ok.csv', index=False)

print("Archivos combinados y guardados correctamente como 'archivo_combinado.csv'")

Archivos combinados y guardados correctamente como 'archivo_combinado.csv'

In [32]:
df_combined

,Url,ID,Nombre,Año,País,Región,Bodega,Tipo de vino,Uva,Precio,Valoración,Contenido de alcohol,Maridajes
0,https://www.vivino.com/ES/es/fr-simonnet-febvr...,3967508,Crémant de Bourgogne Cuvée S Brut,2018,Francia,Crémant de Bourgogne,Simonnet-Febvre,Vino espumoso,"Chardonnay, Pinot Noir",20,3.7,12,"Marisco, Aves, Aperitivos y tentempiés, Pescad..."
1,https://www.vivino.com/ES/es/louis-loron-crema...,4919479,Crémant de Bourgogne Blanc TraditionN.V.,No disponible,Francia,Crémant de Bourgogne,Louis Loron,Vino espumoso,"Chardonnay, Pinot Noir",20,4.0,No disponible,"Marisco, Aves, Aperitivos y tentempiés, Pescad..."
2,https://www.vivino.com/ES/es/marcio-lopes-pequ...,6700139,Pequenos Rebentos Ancestral Loureiro Pet Nat,2022,Portugal,Douro,Márcio Lopes,Vino espumoso,Loureiro,20,4.1,No disponible,"Marisco, Aperitivos y tentempiés, Aperitivo"
3,https://www.vivino.com/ES/es/mestres-coquet-gr...,4311421,Coquet Gran Reserva Brut Nature,2019,España,Cava,Mestres,Vino espumoso,"Macabeo, Xarel-lo, Parellada",15.87,3.9,2,"Marisco, Aperitivos y tentempiés, Pescado blan..."
4,https://www.vivino.com/ES/es/cipriani-bellini-...,5794981,Bellini N.V.,No disponible,Italia,Vino d'Italia,Cipriani,Vino espumoso,No disponible,20,4.2,5,"Aperitivos y tentempiés, Aperitivo"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5478,https://www.vivino.com/ES/es/agrapart-fils-exp...,1455336,EXP. Brut Nature Champagne,2019,Francia,Champán,Agrapart & Fils,Vino espumoso,Chardonnay,342.91,4.3,13,"Cerdo, Marisco, Pescado azul (salmón, atún, et..."
5479,https://www.vivino.com/ES/es/francis-orban-cha...,3979388,Millésimé Champagne,2016,Francia,Champán,Francis Orban,Vino espumoso,"Chardonnay, Pinot Meunier",101.18,4.0,12,"Cerdo, Marisco, Pescado azul (salmón, atún, et..."
5480,https://www.vivino.com/ES/es/r-lenoble-gentilh...,2304743,Gentilhomme Blanc de Blancs Brut Champagne Gra...,No disponible,Francia,Champagne Grand Cru,Lenoble,Vino espumoso,Chardonnay,92,4.3,12,"Cerdo, Marisco, Pescado azul (salmón, atún, et..."
5481,https://www.vivino.com/ES/es/duval-leroy-femme...,11003457,Femme de Champagne Brut Nature,2002,Francia,Champagne Grand Cru,Duval-Leroy,Vino espumoso,"Chardonnay, Pinot Noir",279.99,4.4,12,"Cerdo, Marisco, Pescado azul (salmón, atún, et..."
5482,https://www.vivino.com/ES/es/charles-heidsieck...,1316061,Champagne Charlie,2017,Francia,Champán,Charles Heidsieck,Vino espumoso,"Chardonnay, Pinot Noir, Pinot Meunier",885,4.5,12,"Cerdo, Marisco, Pescado azul (salmón, atún, et..."

In [44]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Pauline\Downloads\Proyecto_grupo2_vinos\espumosos\caracteristicas_espumosos.csv')
df

            ID  Ligero/Poderoso  Débil/Ácido  Amable/Con Burbujas
0      4919479              5.4          5.2                  6.5
1      6700139              4.0          7.3                  5.9
2      4311421              4.2          5.5                  6.0
3      5794981              2.9          4.0                  5.4
4     11816760              3.5          4.3                  4.7
...        ...              ...          ...                  ...
5819   1679094              1.8          5.0                  6.0
5820   1830119              2.0          3.5                  6.2
5821   2971519              3.8          6.5                  5.7
5822   1126336              1.6          6.4                  6.3
5823   1110301              4.6          5.4                  6.4

[5824 rows x 4 columns]

In [47]:
duplicados = df[df.duplicated()]
print(duplicados)

            ID  Ligero/Poderoso  Débil/Ácido  Amable/Con Burbujas
2493   4919479              5.4          5.2                  6.5
2494   6700139              4.0          7.3                  5.9
2495   4311421              4.2          5.5                  6.0
2496   5794981              2.9          4.0                  5.4
2497  11816760              3.5          4.3                  4.7
...        ...              ...          ...                  ...
5819   1679094              1.8          5.0                  6.0
5820   1830119              2.0          3.5                  6.2
5821   2971519              3.8          6.5                  5.7
5822   1126336              1.6          6.4                  6.3
5823   1110301              4.6          5.4                  6.4

[3325 rows x 4 columns]

In [48]:
df = df.drop_duplicates()

In [49]:
df.shape

(2499, 4)

In [ ]:
# Guardar el DataFrame con la columna renombrada en un nuevo archivo CSV
final_df_path = r'C:\Users\Pauline\Downloads\Proyecto_grupo2_vinos\espumosos\caracteristicasesp__ya_hechas.csv'
df.to_csv(final_df_path, index=False)

print(f"Datos guardados en {final_df_path}")

Datos guardados en C:\Users\Pauline\Downloads\Proyecto_grupo2_vinos\espumosos\caracteristicas_esp_ya_hechas.csv

In [57]:
df.shape

(5483, 13)

In [52]:
import pandas as pd

# Rutas de los archivos CSV
caracteristicas_path = r'C:\Users\Pauline\Downloads\Proyecto_grupo2_vinos\espumosos\caracteristicas_esp_ya_hechas.csv'
df_path = r'C:\Users\Pauline\Downloads\Proyecto_grupo2_vinos\espumosos\DF_BF_all_espumosos_ok.csv'

# Leer los CSVs
caracteristicas = pd.read_csv(caracteristicas_path)
df = pd.read_csv(df_path)

# Encontrar los IDs que están en 'DF_BF_all_espumosos_ok.csv' pero no en 'caracteristicas_esp_ya_hechas.csv'
missing_ids = df[~df['ID'].isin(caracteristicas['ID'])]

# Mostrar el resultado
print("IDs que están en 'DF_BF_all_espumosos_ok.csv' pero no en 'caracteristicas_esp_ya_hechas.csv':")
print(missing_ids[['ID']])  # Imprimir solo la columna 'ID'

IDs que están en 'DF_BF_all_espumosos_ok.csv' pero no en 'caracteristicas_esp_ya_hechas.csv':
            ID
0      3967508
42        2615
560    7281247
1169   2176313
1193  10242295
...        ...
5478   1455336
5479   3979388
5480   2304743
5481  11003457
5482   1316061

[1736 rows x 1 columns]